const $=s=>document.querySelector(s),G=(k,d=[])=>JSON.parse(localStorage.getItem("ah_"+k)||JSON.stringify(d)),S=(k,v)=>localStorage.setItem("ah_"+k,JSON.stringify(v));let cur="home";const O=()=>G("orders"),C=()=>G("customers"),I=()=>G("inventory"),E=()=>G("expenses");const M=n=>new Intl.NumberFormat("en-JM",{style:"currency",currency:"JMD",maximumFractionDigits:0}).format(+n||0);
function enter(){let p=$("#pin").value.trim(),s=localStorage.getItem("ah_pin");if(!s){if(p.length<4)return alert("Choose a PIN with 4+ digits.");localStorage.setItem("ah_pin",p);s=p}if(p!==s)return alert("Wrong PIN.");$("#login").hidden=true;$("#app").hidden=false;page("home")}
function page(x){cur=x;render()}function render(){let v=$("#view");if(cur=="home"){let o=O(),e=E(),now=new Date(),mo=o.filter(x=>new Date(x.created).getMonth()==now.getMonth()),sales=mo.reduce((a,x)=>a+x.paid,0),out=mo.reduce((a,x)=>a+Math.max(0,x.price-x.paid),0),ex=e.filter(x=>new Date(x.date).getMonth()==now.getMonth()).reduce((a,x)=>a+x.amount,0),today=new Date().toISOString().slice(0,10);v.innerHTML=`<div class=hero><h2>Good day, Améa babe ✨</h2><div class=meta>Everything in your studio, in one pretty place.</div></div><div class=grid><div class=card>Sales<b>${M(sales)}</b></div><div class=card>Orders<b>${mo.length}</b></div><div class=card>Outstanding<b>${M(out)}</b></div><div class=card>Expenses<b>${M(ex)}</b></div></div><div class=section><h3>Today</h3><div class=card>${list(O().filter(x=>x.due==today),true)||'<div class=meta>No orders due today 💗</div>'}</div></div><div class=section><h3>Quick Actions</h3><div class=quick><button onclick=newOrder()>＋ New Order</button><button onclick=newCustomer()>＋ Customer</button><button onclick=newExpense()>＋ Expense</button><button onclick="page('calendar')">♡ Calendar</button></div></div><div class=section><h3>Recent Orders</h3>${list(O().slice(-5).reverse())||'<div class=empty>No orders yet.</div>'}</div>`}
else if(cur=="orders")v.innerHTML=`<h2>Orders</h2><input placeholder="Search orders, customers, products…" oninput="searchO(this.value)"><div id=ol>${list(O().slice().reverse())||'<div class=empty>No orders yet.</div>'}</div>`;
else if(cur=="customers")v.innerHTML=`<div class=top><h2>Customers</h2><button onclick=newCustomer()>＋ Add</button></div>${C().map(x=>`<div class=item><b>${x.name}</b><div class=meta>${x.phone||""} ${x.email?"· "+x.email:""}<br>${x.measurements||""}</div></div>`).join("")||'<div class=empty>No customers yet.</div>'}`;
else if(cur=="inventory")v.innerHTML=`<div class=top><h2>Inventory</h2><button onclick=newInventory()>＋ Add</button></div>${I().map(x=>`<div class=item><div class=top><b>${x.name}</b><span class=${x.qty<=x.low?"money":""}>${x.qty}</span></div><div class=meta>${x.type}${x.qty<=x.low?" · LOW STOCK":""}</div></div>`).join("")||'<div class=empty>No inventory yet.</div>'}`;
else if(cur=="more")v.innerHTML=`<h2>More</h2><div class=quick><button onclick="page('analytics')">▥ Analytics</button><button onclick="page('expenses')">↘ Expenses</button><button onclick="page('calendar')">♡ Calendar</button><button onclick="page('settings')">⚙ Settings</button></div>`;
else if(cur=="expenses")v.innerHTML=`<div class=top><h2>Expenses</h2><button onclick=newExpense()>＋ Add</button></div>${E().slice().reverse().map(x=>`<div class=item><div class=top><b>${x.category}</b><span class=money>${M(x.amount)}</span></div><div class=meta>${x.date} · ${x.note||""}</div></div>`).join("")||'<div class=empty>No expenses yet.</div>'}`;
else if(cur=="analytics"){let sales=O().reduce((a,x)=>a+x.paid,0),ex=E().reduce((a,x)=>a+x.amount,0);v.innerHTML=`<h2>Analytics</h2><div class=grid><div class=card>Payments<b>${M(sales)}</b></div><div class=card>Expenses<b>${M(ex)}</b></div><div class=card>Est. Profit<b>${M(sales-ex)}</b></div><div class=card>Orders<b>${O().length}</b></div></div>`}
else if(cur=="calendar")v.innerHTML=`<div class=top><h2>Calendar</h2><button onclick=ics()>Add .ics</button></div>${O().filter(x=>x.due).sort((a,b)=>a.due.localeCompare(b.due)).map(x=>`<div class=item><b>${x.due}</b><div class=meta>${x.no} · ${x.customer} · ${x.product} · ${x.delivery}</div></div>`).join("")||'<div class=empty>No due dates yet.</div>'}`;
else if(cur=="settings"){let s=G("settings",{});v.innerHTML=`<h2>Settings</h2><div class=card><label>Email</label><input id=se value="${s.email||""}"><label>WhatsApp / phone</label><input id=sp value="${s.phone||""}"><label>Instagram</label><input id=si value="${s.instagram||""}"><label>Delivery options</label><input id=sd value="${(s.delivery||["Pickup","Delivery"]).join(", ")}"><button class=primary onclick=saveSettings()>Save</button></div><div class="section quick"><button onclick=notify()>Allow Notifications</button><button onclick=backup()>Export Backup</button></div><p class=meta>This build stores data on this device. Export backups regularly.</p>`}}
function list(a){return a.map(x=>`<div class=item onclick="editOrder('${x.id}')"><div class=top><b>${x.no} · ${x.customer}</b><span class=badge>${x.status}</span></div><div class=meta>${x.product} · ${x.size||"—"} · ${x.color||"—"}<br>Payment: ${x.payment} · Delivery: ${x.delivery} · Due: ${x.due||"—"}</div><div class=money>${M(x.paid)} paid · ${M(Math.max(0,x.price-x.paid))} balance</div></div>`).join("")}
function searchO(q){q=q.toLowerCase();$("#ol").innerHTML=list(O().filter(x=>JSON.stringify(x).toLowerCase().includes(q)))}
function openF(h){$("#form").innerHTML=h;dlg.showModal()}function dels(){return G("settings",{}).delivery||["Pickup","Delivery"]}
function newOrder(x={}){openF(`<h2>${x.id?"Edit":"New"} Order</h2><label>Customer</label><input id=oc value="${x.customer||""}"><label>Product</label><input id=op value="${x.product||""}"><div class=row><div><label>Size</label><input id=os value="${x.size||""}"></div><div><label>Color</label><input id=ocol value="${x.color||""}"></div></div><div class=row><div><label>Price</label><input id=opr type=number value="${x.price||""}"></div><div><label>Paid</label><input id=opa type=number value="${x.paid||0}"></div></div><label>Due date</label><input id=od type=date value="${x.due||""}"><label>Payment method</label><select id=opay>${["Cash","Bank transfer","Website"].map(z=>`<option ${x.payment==z?"selected":""}>${z}</option>`)}</select><label>Delivery method</label><select id=odel>${dels().map(z=>`<option ${x.delivery==z?"selected":""}>${z}</option>`)}</select><label>Status</label><select id=ost>${["New","In Studio","Ready","Delivered"].map(z=>`<option ${x.status==z?"selected":""}>${z}</option>`)}</select><label>Private notes</label><textarea id=on>${x.notes||""}</textarea>${x.id?'<label>Reason for edit</label><input id=reason placeholder="Reason required">':""}<button class=primary onclick="saveOrder('${x.id||""}')">Save Order</button>${x.id?`<button class=danger onclick="delOrder('${x.id}')">Delete Order</button>`:""}`)}
function saveOrder(id){let a=O(),old=a.find(x=>x.id==id);if(old&&!$("#reason").value.trim())return alert("Add a reason for the edit.");let seq=+localStorage.getItem("ah_seq")||0,x={id:id||crypto.randomUUID(),no:old?.no||"AM-"+String(seq+1).padStart(4,"0"),customer:oc.value.trim(),product:op.value.trim(),size:os.value,color:ocol.value,price:+opr.value||0,paid:+opa.value||0,due:od.value,payment:opay.value,delivery:odel.value,status:ost.value,notes:on.value,created:old?.created||new Date().toISOString(),history:old?.history||[]};if(!x.customer||!x.product)return alert("Add customer and product.");if(old){x.history.push({at:new Date().toISOString(),reason:reason.value});a=a.map(z=>z.id==id?x:z)}else{localStorage.setItem("ah_seq",seq+1);a.push(x)}S("orders",a);dlg.close();render()}
function editOrder(id){newOrder(O().find(x=>x.id==id))}
function delOrder(id){let r=prompt("Reason for deleting this order?");if(!r)return;let d=G("deleted");d.push({...O().find(x=>x.id==id),deleteReason:r,deletedAt:new Date().toISOString()});S("deleted",d);S("orders",O().filter(x=>x.id!=id));dlg.close();render()}
function newCustomer(){openF(`<h2>Add Customer</h2><label>Name</label><input id=cn><label>Phone</label><input id=cp><label>Email</label><input id=ce><label>Instagram</label><input id=ci><label>Measurements</label><textarea id=cm></textarea><label>Private notes</label><textarea id=cno></textarea><button class=primary onclick=saveCustomer()>Save</button>`)}function saveCustomer(){let a=C();a.push({id:crypto.randomUUID(),name:cn.value,phone:cp.value,email:ce.value,instagram:ci.value,measurements:cm.value,notes:cno.value});S("customers",a);dlg.close();render()}
function newExpense(){openF(`<h2>Add Expense</h2><label>Category</label><select id=ec>${["Yarn/materials","Packaging","Ads","Delivery","Equipment","Other"].map(x=>`<option>${x}</option>`)}</select><label>Amount</label><input id=ea type=number><label>Date</label><input id=ed type=date value="${new Date().toISOString().slice(0,10)}"><label>Note</label><input id=en><button class=primary onclick=saveExpense()>Save</button>`)}function saveExpense(){let a=E();a.push({id:crypto.randomUUID(),category:ec.value,amount:+ea.value||0,date:ed.value,note:en.value});S("expenses",a);dlg.close();render()}
function newInventory(){openF(`<h2>Add Inventory</h2><label>Item</label><input id=ii><label>Type</label><select id=it><option>Material</option><option>Packaging</option><option>Finished product</option></select><label>Quantity</label><input id=iq type=number><label>Low stock alert at</label><input id=il type=number value=2><button class=primary onclick=saveInventory()>Save</button>`)}function saveInventory(){let a=I();a.push({id:crypto.randomUUID(),name:ii.value,type:it.value,qty:+iq.value||0,low:+il.value||2});S("inventory",a);dlg.close();render()}
function saveSettings(){S("settings",{email:se.value,phone:sp.value,instagram:si.value,delivery:sd.value.split(",").map(x=>x.trim()).filter(Boolean)});alert("Saved 💗")}
function notify(){Notification.requestPermission().then(x=>alert(x=="granted"?"Notifications allowed 💗":"Notifications not enabled."))}
function dl(n,d,t){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([d],{type:t}));a.download=n;a.click()}function backup(){dl("amea-hq-backup.json",JSON.stringify({orders:O(),customers:C(),inventory:I(),expenses:E(),settings:G("settings",{}),deleted:G("deleted")},null,2),"application/json")}
function ics(){let a=["BEGIN:VCALENDAR","VERSION:2.0"];O().filter(x=>x.due).forEach(x=>a.push("BEGIN:VEVENT",`UID:${x.id}@ameahq`,`DTSTART;VALUE=DATE:${x.due.replaceAll("-","")}`,`SUMMARY:${x.no} - ${x.customer} - ${x.product}`,"END:VEVENT"));a.push("END:VCALENDAR");dl("amea-orders.ics",a.join("\r\n"),"text/calendar")}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
window.addEventListener("DOMContentLoaded",()=>{lockApp();});
