const K="ameaHQ";let d=JSON.parse(localStorage.getItem(K)||"null")||{orders:[],customers:[],inventory:[],expenses:[],settings:{name:"Améa",delivery:["Pickup","Delivery"]}},page="dashboard";
const nav=[["dashboard","⌂","Home"],["orders","▣","Orders"],["customers","♙","Customers"],["inventory","◌","Inventory"],["analytics","◔","Analytics"],["expenses","₿","Expenses"],["calendar","□","Calendar"],["settings","⚙","Settings"]];
const $=id=>document.getElementById(id),v=id=>$(id)?.value||"",today=()=>new Date().toISOString().slice(0,10),esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),money=x=>new Intl.NumberFormat("en-JM",{style:"currency",currency:"JMD",maximumFractionDigits:0}).format(Number(x)||0);
function save(){localStorage.setItem(K,JSON.stringify(d));render()}function go(p){page=p;render()}
function render(){let ns=nav.map(x=>`<button class="${page==x[0]?"active":""}" onclick="go('${x[0]}')">${x[1]} ${x[2]}</button>`).join("");$("app").innerHTML=`<div class="shell"><aside class="side"><div class="logo">Améa</div><p class="muted">HQ · Business Studio</p><nav class="nav">${ns}</nav></aside><main class="main"><div class="top"><div><h1>${nav.find(x=>x[0]==page)[2]}</h1><span class="muted">Your business, in one place.</span></div><div><button class="secondary" onclick="searchAll()">🔎 Search</button> <button class="primary" onclick="orderModal()">+ New Order</button></div></div>${window[page]()}</main><div class="mobile">${nav.slice(0,5).map(x=>`<button onclick="go('${x[0]}')">${x[1]}<br>${x[2]}</button>`).join("")}</div></div>`}
function dashboard(){let s=d.orders.reduce((a,o)=>a+o.price,0),p=d.orders.reduce((a,o)=>a+o.paid,0),e=d.expenses.reduce((a,x)=>a+x.amount,0);return `<div class="grid"><div class="card"><span class="muted">Sales</span><div class="metric">${money(s)}</div></div><div class="card"><span class="muted">Orders</span><div class="metric">${d.orders.length}</div></div><div class="card"><span class="muted">Outstanding</span><div class="metric">${money(s-p)}</div></div><div class="card"><span class="muted">Expenses</span><div class="metric">${money(e)}</div></div></div><div class="card section"><h2>Today</h2><p class="muted">Due today: ${d.orders.filter(o=>o.due==today()).length} · Pickups/deliveries: ${d.orders.filter(o=>o.fulfilDate==today()).length}</p></div><div class="card section"><h2>Recent Orders</h2>${table(d.orders.slice().reverse().slice(0,6))}</div><div class="card section"><h2>Quick Actions</h2><button class="secondary" onclick="orderModal()">+ New Order</button> <button class="secondary" onclick="customerModal()">+ Customer</button> <button class="secondary" onclick="expenseModal()">+ Expense</button> <button class="secondary" onclick="receiptModal()">🧾 Receipt</button></div>`}
function table(a){if(!a.length)return `<p class="muted">Nothing here yet.</p>`;return `<table class="table"><tr><th>Order</th><th>Customer</th><th>Product</th><th>Due</th><th>Balance</th><th>Status</th><th></th></tr>${a.map(o=>`<tr><td>${o.no}</td><td>${esc(o.customer)}</td><td>${esc(o.product)}</td><td>${o.due||"—"}</td><td>${money(o.price-o.paid)}</td><td><span class="badge">${o.status}</span></td><td><button class="secondary" onclick="orderModal('${o.id}')">Edit</button></td></tr>`).join("")}</table>`}
function orders(){return `<div class="card section"><input id="q" oninput="filter()" placeholder="Search orders..." style="width:100%;padding:12px;border:1px solid #edc7d8;border-radius:11px"><div id="list">${table(d.orders.slice().reverse())}</div></div>`}function filter(){let q=v("q").toLowerCase();$("list").innerHTML=table(d.orders.filter(o=>Object.values(o).join(" ").toLowerCase().includes(q)).reverse())}
function customers(){return `<div class="card section"><div class="row"><h2>Customers</h2><button class="primary" onclick="customerModal()">+ Add</button></div>${d.customers.length?`<table class="table"><tr><th>Name</th><th>Phone</th><th>Email</th><th></th></tr>${d.customers.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${esc(c.email)}</td><td><button class="secondary" onclick="customerModal('${c.id}')">Edit</button></td></tr>`).join("")}</table>`:`<p class="muted">No customers yet.</p>`}</div>`}
function inventory(){return `<div class="card section"><div class="row"><h2>Inventory</h2><button class="primary" onclick="inventoryModal()">+ Add</button></div>${d.inventory.length?`<table class="table"><tr><th>Item</th><th>Type</th><th>Qty</th><th></th></tr>${d.inventory.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.type}</td><td>${i.qty}${i.qty<=i.low?` <span class="badge">Low</span>`:""}</td><td><button class="secondary" onclick="inventoryModal('${i.id}')">Edit</button></td></tr>`).join("")}</table>`:`<p class="muted">No inventory yet.</p>`}</div>`}
function expenses(){return `<div class="card section"><div class="row"><h2>Expenses</h2><button class="primary" onclick="expenseModal()">+ Add</button></div>${d.expenses.length?`<table class="table"><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th></tr>${d.expenses.slice().reverse().map(e=>`<tr><td>${e.date}</td><td>${e.category}</td><td>${esc(e.description)}</td><td>${money(e.amount)}</td></tr>`).join("")}</table>`:`<p class="muted">No expenses yet.</p>`}</div>`}
function analytics(){let s=d.orders.reduce((a,o)=>a+o.price,0),e=d.expenses.reduce((a,x)=>a+x.amount,0);return `<div class="grid"><div class="card"><span class="muted">Sales</span><div class="metric">${money(s)}</div></div><div class="card"><span class="muted">Expenses</span><div class="metric">${money(e)}</div></div><div class="card"><span class="muted">Profit</span><div class="metric">${money(s-e)}</div></div><div class="card"><span class="muted">Orders</span><div class="metric">${d.orders.length}</div></div></div><div class="card"><h2>Business overview</h2><p class="muted">Your numbers update as you add orders and expenses.</p></div>`}
function calendar(){return `<div class="card section"><h2>Upcoming Orders</h2>${table(d.orders.filter(o=>o.due).sort((a,b)=>a.due.localeCompare(b.due)))}</div>`}
function settings(){return `<div class="card section"><h2>Business Info</h2><div class="form"><label class="field">Business name<input id="sn" value="${esc(d.settings.name)}"></label><label class="field">Instagram<input id="si" value="${esc(d.settings.instagram||"")}"></label><label class="field">WhatsApp<input id="sw" value="${esc(d.settings.whatsapp||"")}"></label><label class="field">Email<input id="se" value="${esc(d.settings.email||"")}"></label></div><button class="primary" onclick="saveSettings()">Save</button></div><div class="card section"><h2>Delivery Options</h2>${d.settings.delivery.map((x,i)=>`<div class="row"><input id="del${i}" value="${esc(x)}" style="padding:10px;border:1px solid #edc7d8;border-radius:10px"><button class="danger" onclick="d.settings.delivery.splice(${i},1);save()">Remove</button></div>`).join("")}<br><button class="secondary" onclick="d.settings.delivery.push('New option');save()">+ Add option</button></div><div class="card section"><h2>Backup</h2><button class="secondary" onclick="exportData()">Export data</button></div>`}
function saveSettings(){Object.assign(d.settings,{name:v("sn"),instagram:v("si"),whatsapp:v("sw"),email:v("se")});d.settings.delivery=d.settings.delivery.map((_,i)=>v("del"+i)).filter(Boolean);save()}
function modal(x){document.body.insertAdjacentHTML("beforeend",`<div class="modal"><div>${x}</div></div>`)}function close(){document.querySelector(".modal")?.remove()}
function orderModal(id){let o=d.orders.find(x=>x.id==id)||{id:"",customer:"",product:"",size:"",color:"",price:0,paid:0,due:"",status:"New",payment:"Cash",fulfil:d.settings.delivery[0],fulfilDate:"",notes:""};modal(`<div class="row" style="justify-content:space-between"><h2>${id?"Edit":"New"} Order</h2><button onclick="close()">×</button></div><div class="form"><label class="field">Customer<input id="oc" value="${esc(o.customer)}"></label><label class="field">Product<input id="op" value="${esc(o.product)}"></label><label class="field">Size<input id="os" value="${esc(o.size)}"></label><label class="field">Color<input id="oco" value="${esc(o.color)}"></label><label class="field">Price<input id="opr" type="number" value="${o.price}"></label><label class="field">Paid<input id="opa" type="number" value="${o.paid}"></label><label class="field">Due date<input id="od" type="date" value="${o.due}"></label><label class="field">Status<select id="ost">${["New","In Studio","Ready","Delivered"].map(x=>`<option ${x==o.status?"selected":""}>${x}</option>`).join("")}</select></label><label class="field">Payment<select id="opm">${["Cash","Bank transfer","Website"].map(x=>`<option ${x==o.payment?"selected":""}>${x}</option>`).join("")}</select></label><label class="field">Fulfilment<select id="of">${d.settings.delivery.map(x=>`<option ${x==o.fulfil?"selected":""}>${esc(x)}</option>`).join("")}</select></label><label class="field">Fulfilment date<input id="ofd" type="date" value="${o.fulfilDate}"></label><label class="field full">Notes<textarea id="on">${esc(o.notes)}</textarea></label></div><button class="primary" onclick="saveOrder('${o.id}')">Save Order</button>`)}
function saveOrder(id){let old=d.orders.find(x=>x.id==id),o={id:id||crypto.randomUUID(),no:old?.no||`AM-${String(d.orders.length+1).padStart(4,"0")}`,customer:v("oc"),product:v("op"),size:v("os"),color:v("oco"),price:+v("opr"),paid:+v("opa"),due:v("od"),status:v("ost"),payment:v("opm"),fulfil:v("of"),fulfilDate:v("ofd"),notes:v("on")};if(old)Object.assign(old,o);else d.orders.push(o);close();save()}
function customerModal(id){let c=d.customers.find(x=>x.id==id)||{id:"",name:"",phone:"",email:"",instagram:"",measurements:"",notes:""};modal(`<h2>${id?"Edit":"Add"} Customer</h2><div class="form"><label class="field">Name<input id="cn" value="${esc(c.name)}"></label><label class="field">Phone<input id="cp" value="${esc(c.phone)}"></label><label class="field">Email<input id="ce" value="${esc(c.email)}"></label><label class="field">Instagram<input id="ci" value="${esc(c.instagram)}"></label><label class="field full">Measurements<textarea id="cm">${esc(c.measurements)}</textarea></label><label class="field full">Notes<textarea id="ct">${esc(c.notes)}</textarea></label></div><button class="primary" onclick="saveCustomer('${c.id}')">Save</button> <button class="secondary" onclick="close()">Cancel</button>`)}
function saveCustomer(id){let old=d.customers.find(x=>x.id==id),c={id:id||crypto.randomUUID(),name:v("cn"),phone:v("cp"),email:v("ce"),instagram:v("ci"),measurements:v("cm"),notes:v("ct")};if(old)Object.assign(old,c);else d.customers.push(c);close();save()}
function inventoryModal(id){let i=d.inventory.find(x=>x.id==id)||{id:"",name:"",type:"Materials",qty:0,low:2};modal(`<h2>Inventory</h2><label class="field">Item<input id="in" value="${esc(i.name)}"></label><label class="field">Type<select id="it"><option>Materials</option><option>Packaging</option><option>Finished products</option></select></label><label class="field">Quantity<input id="iq" type="number" value="${i.qty}"></label><label class="field">Low-stock alert<input id="il" type="number" value="${i.low}"></label><button class="primary" onclick="saveInventory('${i.id}')">Save</button>`)}
function saveInventory(id){let old=d.inventory.find(x=>x.id==id),i={id:id||crypto.randomUUID(),name:v("in"),type:v("it"),qty:+v("iq"),low:+v("il")};if(old)Object.assign(old,i);else d.inventory.push(i);close();save()}
function expenseModal(){modal(`<h2>Add Expense</h2><label class="field">Category<select id="ec">${["Yarn/materials","Packaging","Ads","Delivery","Equipment","Other"].map(x=>`<option>${x}</option>`).join("")}</select></label><label class="field">Description<input id="ed"></label><label class="field">Amount<input id="ea" type="number"></label><label class="field">Date<input id="ex" type="date" value="${today()}"></label><button class="primary" onclick="d.expenses.push({id:crypto.randomUUID(),category:v('ec'),description:v('ed'),amount:+v('ea'),date:v('ex')});close();save()">Save</button>`)}
function receiptModal(){modal(`<h2>Receipt</h2><label class="field">Order<select id="ro">${d.orders.map(o=>`<option value="${o.id}">${o.no} — ${esc(o.customer)}</option>`).join("")}</select></label><button class="primary" onclick="receipt()">Create / Print</button>`)}
function receipt(){let o=d.orders.find(x=>x.id==v("ro"));if(!o)return;let w=open("","_blank");w.document.write(`<body style="font-family:Arial;max-width:600px;margin:40px auto"><h1 style="font:42px Georgia;color:#e52f7e">Améa</h1><h2>Receipt ${o.no}</h2><p>Customer: ${esc(o.customer)}<br>Product: ${esc(o.product)}<br>Payment: ${o.payment}</p><h3>Total: ${money(o.price)}</h3><p>Paid: ${money(o.paid)}<br>Balance: ${money(o.price-o.paid)}</p><button onclick="print()">Print / Save PDF</button></body>`);w.document.close()}
function searchAll(){let q=prompt("Search Améa HQ");if(!q)return;let r=[...d.orders,...d.customers,...d.inventory].filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase()));alert(r.length+" result(s) found.")}
function exportData(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:"application/json"}));a.download="amea-hq-backup.json";a.click()}
render();